-- +goose Up
ALTER TABLE job_specialties
    ADD COLUMN definition TEXT NOT NULL DEFAULT '',
    ADD COLUMN include_signals JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN exclude_signals JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN confused_with JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE job_description_classifications
    ADD COLUMN reason TEXT NOT NULL DEFAULT '';

ALTER TABLE analysis_jobs
    ADD COLUMN preserve_previous_result BOOLEAN NOT NULL DEFAULT FALSE;

WITH specialty_data(code, definition, include_signals, exclude_signals, confused_with) AS (VALUES
('backend-business',
 '面向具体产品或业务域设计并实现服务端业务逻辑、接口、数据模型和业务流程。',
 '["负责业务接口、领域逻辑或交易流程的设计与实现","建设面向用户或运营场景的服务端功能","处理业务数据一致性、权限或业务规则"]'::jsonb,
 '["仅出现 Go、Java、MySQL、Redis 等技术名词","只负责通用框架、网关、RPC 或中间件研发","只描述内部研发平台而没有具体业务流程"]'::jsonb,
 '[{"specialty_code":"backend-framework-middleware","distinction":"业务后端以具体产品和业务规则为对象；框架与中间件以通用基础组件为交付物。"},{"specialty_code":"backend-developer-platform","distinction":"业务后端直接承载业务流程；开发者平台主要服务内部研发人员和工程流程。"}]'::jsonb),
('backend-framework-middleware',
 '研发供多个业务复用的服务框架、RPC、网关、消息、缓存或分布式中间件。',
 '["设计或维护 RPC、服务治理、网关、消息队列等通用组件","优化中间件的性能、可靠性或一致性","为多个业务团队提供统一服务框架能力"]'::jsonb,
 '["业务中使用了 Redis、Kafka 或 RPC","只做普通接口开发或业务功能迭代","仅负责云资源部署和运维"]'::jsonb,
 '[{"specialty_code":"backend-business","distinction":"是否以跨业务复用的基础组件为主要交付物。"},{"specialty_code":"infra-cloud","distinction":"框架与中间件聚焦应用运行时组件；云平台聚焦计算、网络、容器和资源管理。"}]'::jsonb),
('backend-developer-platform',
 '建设面向研发人员的内部平台、开放平台后端、工程效率工具及其服务端能力。',
 '["建设研发效能、配置、发布、低代码或开放平台后端","设计供开发者使用的 API、控制台或工具服务","整合代码、构建、部署、质量等研发流程"]'::jsonb,
 '["普通业务后台管理系统","仅编写脚本或使用现成 CI 工具","只因岗位名称含平台二字"]'::jsonb,
 '[{"specialty_code":"backend-business","distinction":"服务对象主要是开发者和研发流程，而非具体消费或企业业务。"},{"specialty_code":"frontend-engineering","distinction":"开发者平台以后端服务与流程编排为核心；前端工程化以构建链路和组件体系为核心。"}]'::jsonb),
('frontend-web-miniapp',
 '开发面向用户的 Web 页面、小程序和浏览器端交互功能。',
 '["实现网页或小程序页面、交互和状态管理","对接业务接口并完成用户端功能","处理浏览器兼容、性能与用户体验"]'::jsonb,
 '["仅出现 JavaScript、TypeScript 或 React","主要建设构建工具、组件平台或跨端运行时","主要负责桌面或移动原生客户端"]'::jsonb,
 '[{"specialty_code":"frontend-engineering","distinction":"Web 与小程序前端交付具体用户功能；前端工程化交付工具链和复用基础设施。"},{"specialty_code":"client-cross-platform","distinction":"Web 小程序运行于浏览器或小程序容器；跨端客户端强调多端原生应用交付。"}]'::jsonb),
('frontend-engineering',
 '建设前端构建体系、组件平台、研发工具、质量体系和工程基础设施。',
 '["研发脚手架、构建工具、组件库或微前端基础设施","制定前端工程规范并提升构建发布效率","建设跨项目复用的前端研发平台"]'::jsonb,
 '["只开发具体页面或活动功能","仅使用 Webpack、Vite 等现成工具","仅维护普通后台管理界面"]'::jsonb,
 '[{"specialty_code":"frontend-web-miniapp","distinction":"工程化以跨项目复用的工具和体系为产出，而非单个页面功能。"},{"specialty_code":"backend-developer-platform","distinction":"前端工程化聚焦前端构建与组件生态；开发者平台后端聚焦研发流程服务。"}]'::jsonb),
('frontend-visualization-graphics',
 '在浏览器或前端运行时实现数据可视化、图形渲染、编辑器或交互式图形应用。',
 '["研发图表、地图、Canvas、WebGL 或可视化编辑器","优化前端图形渲染性能和交互体验","实现复杂二维或三维可视化场景"]'::jsonb,
 '["普通页面中使用了图表组件","只做数据报表接口或离线统计","主要研发游戏引擎或原生图形运行时"]'::jsonb,
 '[{"specialty_code":"frontend-web-miniapp","distinction":"可视化与图形前端以图形渲染或编辑能力为核心，而非一般页面交互。"},{"specialty_code":"game-engine-tools","distinction":"前端图形运行在 Web 场景；游戏引擎工具服务游戏内容和实时运行时。"}]'::jsonb),
('client-mobile',
 '开发 iOS、Android 等移动端原生应用及其性能、架构和平台能力。',
 '["负责 iOS 或 Android 原生功能与架构","优化移动端启动、内存、耗电或稳定性","建设移动端基础组件和系统能力"]'::jsonb,
 '["只出现 App 或移动互联网字样","主要使用 Flutter、React Native 同时覆盖多端","主要开发设备固件或硬件控制逻辑"]'::jsonb,
 '[{"specialty_code":"client-cross-platform","distinction":"移动客户端强调单一移动平台原生能力；跨端客户端强调一套技术覆盖多个终端。"},{"specialty_code":"embedded-device-application","distinction":"移动客户端运行于通用手机系统；设备应用面向专用硬件和设备业务。"}]'::jsonb),
('client-desktop',
 '开发 Windows、macOS、Linux 桌面应用及其原生集成和性能体验。',
 '["实现桌面端业务功能和窗口交互","处理操作系统集成、安装升级或桌面性能","建设桌面客户端架构与基础组件"]'::jsonb,
 '["仅有 Web 管理后台","只因使用 Electron 就忽略实际交付端","主要开发系统内核、驱动或编译器"]'::jsonb,
 '[{"specialty_code":"client-cross-platform","distinction":"桌面客户端以桌面平台体验为核心；跨端客户端以多终端复用为核心。"},{"specialty_code":"frontend-web-miniapp","distinction":"桌面客户端需要桌面系统集成和应用生命周期，Web 前端主要运行于浏览器。"}]'::jsonb),
('client-cross-platform',
 '使用跨端框架或自研运行时同时交付移动、桌面、Web 等多个终端。',
 '["建设 Flutter、React Native、Electron 或自研跨端方案","维护多端共享业务层、渲染层或跨端运行时","解决多平台适配与一致体验问题"]'::jsonb,
 '["仅在一个平台使用跨端框架开发普通功能","普通响应式网页适配手机与桌面","只维护单一 iOS、Android 或桌面应用"]'::jsonb,
 '[{"specialty_code":"client-mobile","distinction":"跨端职责必须体现多个终端的共享和适配，而非单一移动端。"},{"specialty_code":"frontend-web-miniapp","distinction":"跨端客户端交付安装型或原生容器应用，普通 Web 适配不足以归类。"}]'::jsonb),
('ai-rag-knowledge-base',
 '围绕检索增强生成、知识库、文档解析和检索评测构建 AI 应用。',
 '["设计文档切分、索引、召回、重排和生成链路","建设企业知识库问答或搜索增强应用","评估并优化检索质量、引用和回答可靠性"]'::jsonb,
 '["仅出现向量数据库、Embedding 或大模型关键词","只是调用搜索接口或普通数据库查询","主要职责是 Agent 工具编排且无知识检索链路"]'::jsonb,
 '[{"specialty_code":"ai-agent-application","distinction":"RAG 以知识检索和有依据生成为主链路；Agent 以自主决策和工具调用为主链路。"},{"specialty_code":"ai-application-platform","distinction":"RAG 交付具体检索应用；AI 应用平台提供多应用复用的模型与评测能力。"}]'::jsonb),
('ai-agent-application',
 '构建能够规划步骤、调用工具、维护状态并完成业务任务的 Agent 应用。',
 '["设计 Agent 工具调用、任务规划、记忆或状态管理","把业务操作封装为受控工具并处理调用结果","建设多 Agent 协作、执行恢复或 Agent 评测"]'::jsonb,
 '["仅使用大模型聊天或 Prompt","只出现 Agent、Function Calling、MCP 名词","主要工作是知识库检索而没有工具执行和任务闭环"]'::jsonb,
 '[{"specialty_code":"ai-rag-knowledge-base","distinction":"Agent 核心是决策与执行闭环；RAG 核心是知识检索与有依据回答。"},{"specialty_code":"ai-application-platform","distinction":"Agent 应用解决具体业务任务；AI 应用平台向多个应用提供通用运行与治理能力。"}]'::jsonb),
('ai-application-platform',
 '建设支撑多个 AI 应用的模型接入、Prompt、评测、观测、安全和运行平台。',
 '["建设统一模型网关、Prompt 管理、评测或可观测平台","提供多租户 AI 应用编排、发布和治理能力","管理模型调用成本、配额、安全和版本"]'::jsonb,
 '["单个聊天机器人或单一业务 Agent","只封装一次模型 API 调用","主要建设训练推理集群等底层 AI 基础设施"]'::jsonb,
 '[{"specialty_code":"ai-agent-application","distinction":"平台能力被多个 Agent 或 AI 应用复用，具体 Agent 业务不等于平台。"},{"specialty_code":"infra-ai","distinction":"AI 应用平台面向应用开发与治理；AI 基础设施面向训练推理算力和系统。"}]'::jsonb),
('data-offline-warehouse',
 '建设离线数据采集、ETL、数仓分层、批处理和指标生产链路。',
 '["设计离线 ETL、数仓模型和批处理任务","维护数据仓库分层、调度和离线指标","优化 Spark、Hive 等批处理链路"]'::jsonb,
 '["普通业务数据库增删改查","只写少量统计 SQL 或报表","核心是秒级流式计算和实时链路"]'::jsonb,
 '[{"specialty_code":"data-realtime","distinction":"离线数仓以批次和周期性产出为主；实时处理强调低延迟流式计算。"},{"specialty_code":"data-platform-governance","distinction":"离线数仓生产数据和指标；数据平台治理提供元数据、质量和统一管理能力。"}]'::jsonb),
('data-realtime',
 '建设消息驱动的实时采集、流式计算、实时指标和低延迟数据链路。',
 '["研发 Flink、Kafka Streams 等实时计算任务","建设实时数仓、事件流或秒级指标链路","处理流式状态、一致性、乱序和延迟问题"]'::jsonb,
 '["业务系统使用 Kafka 传递消息","定时批处理或离线 ETL","普通接口需要低响应延迟"]'::jsonb,
 '[{"specialty_code":"data-offline-warehouse","distinction":"实时处理以持续事件流和低延迟为核心，离线数仓以批次任务为核心。"},{"specialty_code":"backend-framework-middleware","distinction":"使用消息中间件承载业务不等于负责实时数据计算。"}]'::jsonb),
('data-platform-governance',
 '建设数据开发平台、元数据、质量、血缘、权限和数据治理体系。',
 '["建设数据开发、调度、元数据或数据质量平台","实现数据血缘、资产目录、权限和治理规则","为多类数据任务提供统一平台能力"]'::jsonb,
 '["单个离线或实时任务开发","普通后台中的数据管理页面","只做业务数据库表设计"]'::jsonb,
 '[{"specialty_code":"data-offline-warehouse","distinction":"数据平台治理提供跨任务管理能力；离线数仓侧重具体数据生产链路。"},{"specialty_code":"backend-developer-platform","distinction":"数据平台面向数据资产和数据任务；开发者平台面向通用软件研发流程。"}]'::jsonb),
('testing-automation',
 '设计并实现自动化测试用例、框架和持续测试流程以验证产品功能。',
 '["编写接口、UI、端到端或回归自动化测试","搭建自动化测试框架并接入持续集成","提升功能测试覆盖率和缺陷发现效率"]'::jsonb,
 '["普通开发者编写单元测试","只执行手工测试用例","主要研发通用测试平台而非具体测试自动化"]'::jsonb,
 '[{"specialty_code":"testing-tools-platform","distinction":"自动化测试直接验证产品功能；测试工具平台向测试活动提供复用基础设施。"},{"specialty_code":"testing-performance-stability","distinction":"自动化测试侧重功能正确性；性能稳定性测试侧重负载、故障和可靠性。"}]'::jsonb),
('testing-performance-stability',
 '通过性能、压力、故障和稳定性测试发现系统容量与可靠性问题。',
 '["设计压测、容量评估、故障注入或稳定性测试","分析性能瓶颈、资源使用和长期运行问题","建设可靠性验证和线上质量防护方案"]'::jsonb,
 '["业务开发中的一般性能优化","只使用监控查看指标","普通功能自动化测试"]'::jsonb,
 '[{"specialty_code":"testing-automation","distinction":"性能稳定性测试关注容量和故障表现，而非一般功能回归。"},{"specialty_code":"testing-tools-platform","distinction":"性能测试执行具体评估；测试平台提供通用工具和环境。"}]'::jsonb),
('testing-tools-platform',
 '研发测试管理、数据、环境、设备、覆盖率等通用测试工具与平台。',
 '["建设测试管理、测试数据或测试环境平台","研发覆盖率、Mock、设备云或质量工具","为多个团队提供统一测试基础设施"]'::jsonb,
 '["只编写某项业务的自动化用例","使用现成测试平台执行任务","普通研发效能平台且不服务测试流程"]'::jsonb,
 '[{"specialty_code":"testing-automation","distinction":"测试平台以跨团队复用工具为产出；自动化测试以具体产品验证为产出。"},{"specialty_code":"backend-developer-platform","distinction":"测试平台专注质量与测试流程；开发者平台覆盖更广的研发流程。"}]'::jsonb),
('infra-database-storage',
 '研发数据库内核、分布式存储、缓存引擎或持久化系统的核心能力。',
 '["开发数据库或存储引擎、查询执行、事务或复制机制","研发分布式文件、对象、块存储或缓存系统","优化存储系统的一致性、可靠性和性能"]'::jsonb,
 '["业务中使用 MySQL、Redis 或对象存储","普通数据库表设计和 SQL 优化","只建设数据治理或业务数据平台"]'::jsonb,
 '[{"specialty_code":"backend-framework-middleware","distinction":"数据库存储研发以数据引擎和持久化机制为核心；中间件以应用通信和治理组件为核心。"},{"specialty_code":"data-platform-governance","distinction":"存储研发建设底层数据系统；数据平台治理管理数据资产和任务。"}]'::jsonb),
('infra-os-compiler-runtime',
 '研发操作系统、编译器、语言运行时、虚拟机和相关底层系统软件。',
 '["开发内核、文件系统、调度、内存或系统调用能力","研发编译器前后端、优化器、虚拟机或语言运行时","进行底层系统性能与工具链研发"]'::jsonb,
 '["仅在 Linux 环境开发或写 Shell","普通应用使用 JVM、Go runtime 或编译工具","主要开发设备驱动和硬件固件"]'::jsonb,
 '[{"specialty_code":"embedded-system","distinction":"操作系统与运行时面向通用系统软件；嵌入式系统围绕受限设备和硬件平台。"},{"specialty_code":"game-engine-tools","distinction":"编译运行时是通用底层系统；游戏引擎围绕游戏内容和实时渲染。"}]'::jsonb),
('infra-cloud',
 '建设云计算、容器、编排、网络、资源调度和基础设施管理平台。',
 '["研发容器、Kubernetes、服务网格或云资源管理能力","建设计算、网络、负载均衡或资源调度平台","提升大规模基础设施的可靠性和自动化"]'::jsonb,
 '["仅会使用 Docker 或部署应用","普通业务服务运行在云上","只开发 RPC、网关等应用层中间件"]'::jsonb,
 '[{"specialty_code":"backend-framework-middleware","distinction":"云平台管理基础资源和运行环境；中间件提供应用层通信与治理能力。"},{"specialty_code":"infra-ai","distinction":"云平台服务通用工作负载；AI 基础设施针对训练推理和模型工作负载。"}]'::jsonb),
('infra-ai',
 '研发模型训练、推理、算力调度、分布式计算和 AI 系统基础设施。',
 '["建设分布式训练、推理引擎或模型服务系统","优化 GPU 算力、通信、编译和推理性能","研发 AI 集群调度、模型部署或训练平台底层能力"]'::jsonb,
 '["仅调用大模型 API 或开发 AI 应用","普通云平台中部署一个模型服务","只做 Prompt、RAG 或 Agent 业务逻辑"]'::jsonb,
 '[{"specialty_code":"ai-application-platform","distinction":"AI 基础设施面向模型计算和系统性能；AI 应用平台面向应用接入、评测和治理。"},{"specialty_code":"infra-cloud","distinction":"AI 基础设施专门优化训练推理工作负载；云平台服务通用资源。"}]'::jsonb),
('embedded-firmware-driver',
 '开发芯片、板卡和外设相关的固件、Bootloader、BSP 与设备驱动。',
 '["编写 MCU 固件、Bootloader、BSP 或硬件驱动","调试总线、寄存器、中断和外设接口","完成硬件 bring-up 与底层适配"]'::jsonb,
 '["仅使用 C/C++ 开发","普通 Linux 应用调用设备接口","主要负责设备上层业务和交互"]'::jsonb,
 '[{"specialty_code":"embedded-system","distinction":"固件驱动直接面向硬件和外设；嵌入式系统负责系统服务、资源和整体软件架构。"},{"specialty_code":"embedded-device-application","distinction":"固件驱动位于设备底层；设备应用实现面向用户或行业的上层功能。"}]'::jsonb),
('embedded-system',
 '构建面向专用设备的嵌入式操作环境、系统服务、通信和整体软件架构。',
 '["设计嵌入式 Linux、RTOS 系统服务或软件架构","处理设备资源、进程、通信、升级和稳定性","整合驱动、中间层与上层应用形成设备系统"]'::jsonb,
 '["只开发单个硬件驱动或 MCU 固件","普通服务器 Linux 后端开发","只实现设备界面或业务功能"]'::jsonb,
 '[{"specialty_code":"embedded-firmware-driver","distinction":"嵌入式系统负责系统级架构与服务；固件驱动直接控制硬件。"},{"specialty_code":"embedded-device-application","distinction":"嵌入式系统提供设备运行基础；设备应用实现具体产品功能。"}]'::jsonb),
('embedded-device-application',
 '在智能硬件、车载、机器人、IoT 等专用设备上实现具体产品和行业应用。',
 '["开发车载、机器人、IoT 或智能设备业务功能","实现设备交互、控制策略和行业场景逻辑","对接设备系统能力完成完整产品功能"]'::jsonb,
 '["仅编写底层驱动或系统服务","普通手机 App 控制一个设备","只因岗位涉及硬件或 IoT 协议"]'::jsonb,
 '[{"specialty_code":"embedded-system","distinction":"设备应用面向具体产品功能；嵌入式系统面向设备运行基础。"},{"specialty_code":"client-mobile","distinction":"设备应用运行于专用硬件；移动客户端运行于通用手机平台。"}]'::jsonb),
('game-client',
 '开发游戏客户端玩法、界面、网络同步和运行性能。',
 '["实现游戏玩法、UI、角色或客户端系统","处理客户端网络同步、资源和性能优化","使用 Unity、Unreal 或自研引擎交付具体游戏内容"]'::jsonb,
 '["仅出现 C++、Unity 或图形渲染关键词","主要研发引擎编辑器和通用工具","普通桌面或移动应用开发"]'::jsonb,
 '[{"specialty_code":"game-engine-tools","distinction":"游戏客户端交付具体玩法和内容；引擎工具提供多项目复用的底层能力。"},{"specialty_code":"client-desktop","distinction":"游戏客户端围绕实时玩法和游戏系统，普通桌面客户端不具备该职责。"}]'::jsonb),
('game-server',
 '开发支撑在线游戏玩法、玩家状态、匹配、战斗和运营活动的服务端系统。',
 '["实现游戏房间、匹配、战斗或玩家状态服务","处理游戏实时通信、同步和高并发在线逻辑","建设游戏活动、经济或运营服务端系统"]'::jsonb,
 '["普通业务后端使用长连接或高并发","只因公司属于游戏行业","主要开发通用网关、中间件或数据库"]'::jsonb,
 '[{"specialty_code":"backend-business","distinction":"游戏服务端必须体现玩法、玩家或游戏运营领域职责，行业名称本身不足以分类。"},{"specialty_code":"backend-framework-middleware","distinction":"游戏服务端承载游戏业务；框架中间件提供跨业务复用组件。"}]'::jsonb),
('game-engine-tools',
 '研发游戏引擎、渲染、物理、动画、资源管线、编辑器和内容生产工具。',
 '["开发渲染、物理、动画或游戏引擎核心模块","建设关卡、资源、编辑器和内容生产工具链","优化引擎运行时和跨平台底层能力"]'::jsonb,
 '["仅使用 Unity 或 Unreal 开发玩法","普通前端 Canvas 或 WebGL 页面","只开发具体游戏客户端 UI 和逻辑"]'::jsonb,
 '[{"specialty_code":"game-client","distinction":"引擎工具提供跨内容复用的底层和生产能力；游戏客户端实现具体玩法。"},{"specialty_code":"frontend-visualization-graphics","distinction":"游戏引擎面向游戏运行时和内容生产；前端图形主要面向 Web 可视化应用。"}]'::jsonb)
)
UPDATE job_specialties specialty
SET definition = data.definition,
    include_signals = data.include_signals,
    exclude_signals = data.exclude_signals,
    confused_with = data.confused_with,
    updated_at = NOW()
FROM specialty_data data
WHERE specialty.code = data.code;

ALTER TABLE job_specialties
    ADD CONSTRAINT job_specialties_definition_present CHECK (length(trim(definition)) > 0),
    ADD CONSTRAINT job_specialties_include_signals_array CHECK (jsonb_typeof(include_signals) = 'array' AND jsonb_array_length(include_signals) > 0),
    ADD CONSTRAINT job_specialties_exclude_signals_array CHECK (jsonb_typeof(exclude_signals) = 'array' AND jsonb_array_length(exclude_signals) > 0),
    ADD CONSTRAINT job_specialties_confused_with_array CHECK (jsonb_typeof(confused_with) = 'array' AND jsonb_array_length(confused_with) > 0);

UPDATE analysis_jobs job
SET status = 'queued', attempts = 0, next_attempt_at = NOW(),
    locked_at = NULL, lease_token = NULL, heartbeat_at = NULL,
    lease_expires_at = NULL, last_error = NULL,
    preserve_previous_result = TRUE, updated_at = NOW()
FROM job_descriptions jd
WHERE job.job_description_id = jd.id
  AND job.job_type = 'jd_analysis'
  AND job.status = 'succeeded'
  AND jd.validation_status = 'valid'
  AND COALESCE(jd.analysis_prompt_version, '') <> 'jd-classification-v3';

-- +goose Down
ALTER TABLE analysis_jobs DROP COLUMN IF EXISTS preserve_previous_result;
ALTER TABLE job_description_classifications DROP COLUMN IF EXISTS reason;
ALTER TABLE job_specialties
    DROP CONSTRAINT IF EXISTS job_specialties_confused_with_array,
    DROP CONSTRAINT IF EXISTS job_specialties_exclude_signals_array,
    DROP CONSTRAINT IF EXISTS job_specialties_include_signals_array,
    DROP CONSTRAINT IF EXISTS job_specialties_definition_present,
    DROP COLUMN IF EXISTS confused_with,
    DROP COLUMN IF EXISTS exclude_signals,
    DROP COLUMN IF EXISTS include_signals,
    DROP COLUMN IF EXISTS definition;
